### ISSUE TITLE
Update README May 2023

### ISSUE THREAD

**Issue by TheStrangerDoctor** [alvindrakes/veggie_go_malaysia#29]
Hello, this project has some potential however you did not provide enough or any instructions in the readme. This can cause a few things:

1) Nobody understands what are you trying to do
2) Nobody can help you contribute in fixing errors or improve the code
3) Difficulty to maintain when the project gets larger, eventually leading to burnout => "close project"

I hope you can consider updating this repo especially the readme as there may be good potential for this project to be advertised to vegans in Malaysia. Thank you!

**Comment by alvindrakes** [comment]
@TheStrangerDoctor Hey doctor!

Glad that you're interested in the project.

We initially built this project for the "vegan society" NGO in Malaysia but due to financial and time constraints, it was abandoned and stopped. 

You are free to fork the project and build it for them if you want to. 

Let me know if you have any questions 😄
